import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/testing/index.ts",
    "src/store/index.ts",
    "src/react/index.ts",
    "src/seeds/index.ts",
    "src/adapters/index.ts",
    "src/drizzle/index.ts",
    "src/workshop/index.ts",
    "src/express/index.ts",
    "src/nest/index.ts",
    "src/ports/index.ts",
    "src/client/index.ts",
  ],
  format: ["esm", "cjs"],
  dts: false,
  sourcemap: true,
  clean: true,
  external: [
    "drizzle-orm",
    "drizzle-orm/better-sqlite3",
    "drizzle-orm/pg-core",
    "drizzle-orm/sqlite-core",
    "better-sqlite3",
    "react",
    "@tanstack/react-query",
    "@eristack/jwt-auth",
    "@eristack/jwt-auth/backseat",
    "@eristack/epoch/backseat",
    "@eristack/pbac",
    "@eristack/pbac/backseat",
    "@eristack/qups/backseat",
    "express",
    "@nestjs/common",
  ],
});
