export {
  isKeyTargetOutsideActiveGrid,
  isPointerTargetOutsideGrids,
  SpreadsheetGridIdProvider,
  SpreadsheetNavCell,
  SpreadsheetScopeProvider,
  SpreadsheetTable,
  SpreadsheetTextCell,
  useSpreadsheetCellEditor,
  useSpreadsheetGrid,
  useSpreadsheetGridId,
  useSpreadsheetScope,
  type KeyTargetLike,
  type SpreadsheetCellEditor,
  type SpreadsheetGridIdProviderProps,
  type SpreadsheetNavCellProps,
  type SpreadsheetScopeApi,
  type SpreadsheetScopeProviderProps,
  type SpreadsheetTableProps,
  type SpreadsheetTextCellProps,
  type UseSpreadsheetCellEditorOptions,
  type UseSpreadsheetGridResult,
} from "./scope.js";
