export {
  createRestRouter,
  defineRoutes,
  toOpenApiDocument,
  mergeOpenApiDocuments,
  type HttpMethod,
  type OpenApiDocument,
  type OpenApiEmitOptions,
  type RestDispatchResult,
  type RestHandler,
  type RestHandlerContext,
  type RestResponse,
  type RestRouteDef,
  type RestRouter,
} from "./core/router.js";
